name: my-hello-python
base: core20
version: '0.1'
summary: A simple Python snap
description: |
  An example showing how Python programs can be packaged as snaps.

grade: stable
confinement: strict

apps:
  my-hello-python:
    command: bin/hello

parts:
  my-program:
    plugin: dump
    source: .
    organize:
      hello.py: bin/hello

